#max-professions: 2
#menu-name: "Выберите проффесию"

default-prof-points: 5

groups:
  1:
    - warrior
    - bow-master
  2:
    - healer
    - farmer
  3:
    - remeslennik
    - kuznec

professions:
  warrior:
    name: "&cВоин"
    slot: 12
    command: "say some one got warrior"
    permission: "test.permission.warrior"
    material: DIRT
    cost: 3
    banned:
      - healer
    lore:
      - "&cline 1"
      - line 2
  bow-master:
    name: "&cЛучник"
    slot: 13
    command: "say some one got warrior"
    permission: "test.permission.bow_master"
    material: DIRT
    cost: 3
    banned:
      - healer
    lore:
      - "&cline 1"
      - line 2
  healer:
    name: "&cМедсестра"
    slot: 14
    command: "say %player% some one got medichka"
    permission: "test.healer"
    material: DIRT
    cost: 3
    banned:
      - farmer
    lore:
      - "&cline 1"
      - line 2
  farmer:
    name: Фермер
    cost: 2
    slot: 15
    command: "say some one got farmer"
    permission: "test.permission.farmer"
    material: DIRT
    lore:
      - line 1
      - line 2
  remeslennik:
    name: Ремесленник
    cost: 2
    slot: 16
    command: "say some one got farmer"
    permission: "test.permission.farmer"
    material: DIRT
    lore:
      - line 1
      - line 2
  kuznec:
    name: Кузнец
    cost: 2
    slot: 17
    command: "say some one got farmer"
    permission: "test.permission.farmer"
    material: DIRT
    lore:
      - line 1
      - line 2