#max-professions: 2
#menu-name: "Выберите проффесию"

default-prof-points: 5
show-groups-after-loading: true
show-professions-after-loading: true


groups:
  1:
    - warrior
    - bow-master
  2:
    - healer
    - farmer
  3:
    - remeslennik
    - kuznec

professions:
  warrior:
    name: "&cВоин"
    slot: 19
    command: "say %player% 1" #%player%
    permission: "profession.warrior"
    material: "IRON_AXE"
    cost: 3
    banned:
      - "healer"
    lore:
      - "&cline 1"
      - "line 2"
  bow-master:
    name: "&cЛучник"
    slot: 28
    cost: 3
    command: "say %player% 2" #%player%
    permission: "profession.bow_master"
    material: "BOW"
    banned:
      - "healer"
    lore:
      - "&cline 1"
      - "line 2"
  healer:
    name: "&cМедсестра"
    slot: 21
    cost: 3
    command: "say %player% 3" #%player%
    permission: "profession.healer"
    material: "POISONOUS_POTATO"
    banned:
      - "farmer"
    lore:
      - "&cline 1"
      - "line 2"
  farmer:
    name: "Фермер"
    cost: 2
    slot: 30
    command: "say %player% 4"
    permission: "profession.farmer"
    material: "IRON_HOE"
    lore:
      - "line 1"
      - "line 2"
  remeslennik:
    name: "Ремесленник"
    cost: 2
    slot: 23
    command: "say %player% 5"
    permission: "profession.remeslennik"
    material: "STONE_PICKAXE"
    lore:
      - "line 1"
      - "line 2"
  kuznec:
    name: "Кузнец"
    cost: 0
    slot: 32
    command: "say %player% 6"
    permission: "profession.kuznec"
    material: "DIAMOND_PICKAXE"
    lore:
      - "line 1"
      - "line 2"